### ISSUE TITLE
Dynamically load Client and Realm

### ISSUE THREAD

**Issue by febincloudyuga** [ccrockett/omniauth-keycloak#11]
Hi,

This gem has been extremely helpful, but I'm missing a major piece to complete my implementation.

My use-case is a multi tenant approach, where the Realm and Client are expected to change.

I'm using this gem alongside of Devise and this line of `devise.rb` is loaded loaded only once when the application starts
```config.omniauth :keycloak_openid, "Example-Client-Name", "example-secret-if-configured", client_options: { site: "https://example.keycloak-url.com", realm: "example-realm" }, :strategy_class => OmniAuth::Strategies::KeycloakOpenId```

I'm forced to have a single client in this case.

Is there a possibility where I can dynamically configure the Client and Realm per request?

Any pointers on how to go about this would be really helpful.

Thanks

**Comment by ccrockett** [comment]
I don't think there is any way do that dynamically while using omni-auth (which my gem is built on top of). You can certainly do this with keycloak but you can't use my gem in that case.

**Comment by cedrtang** [comment]
For those looking to do this, the `setup_phase` of OmniAuth Strategy originally allowed to pass a Rack function to the `:setup` argument like this for example:

`def setup_provider_proc()
  lambda do |env|
    request = Rack::Request.new(env)
     env["omniauth.strategy"].options[:client_id] = request.params[:client_id]
     env["omniauth.strategy"].options[:client_options][:realm] = request.params[:realm]
     ...

  end
end

provider(
        :keycloak_openid,
        setup: setup_provider_proc()
        )
`

You just have to add `super` to the top of the `setup_phase` in this gem to call the native `setup_phase`
