### ISSUE TITLE
No route matches [POST] "/auth/keycloak_openid"

### ISSUE THREAD

**Issue by andreasBasis** [ccrockett/omniauth-keycloak#15]
Hi, 
first of all thanks for this gem.

I just create a new rails 6.1 project and first thing to me is to get auth working.. so there is nothing installed except this gem plus its dependencies..

i have configured this initializer:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :keycloak_openid, 'xxxCLIENTxxx', 'xxxKEYxxx',
           client_options: {site: 'https://auth.xxxDOMAINxxx.com', realm: 'xxxREALMxxx'}
end
```
this route:

`post '/auth/:provider/callback', to: 'sessions#create'`

and just for testing a quick and dirty 

`<%= button_to 'Sign In', '/auth/keycloak_openid' %>`

to get the ball rolling.. i click on it and get this `No route matches [POST] "/auth/keycloak_openid"`error.

however, Omniauth is present and its config suggests the `keycloak_openid` provider is too:

![image](https://user-images.githubusercontent.com/13486613/126892118-6794a0b6-20e0-4c25-b114-491b7636b7ee.png)

i also gave `auth/keycloak` a shot (yeah, proly made no sense, but just in case)... - same thing

idk what i did wrong here, maybe its a bug (with rails 6.1)..(?)

**Comment by awunder** [comment]
fwiw, i added the `omniauth-twitter` gem and `/auth/twitter` is happily responding..

so, we could rule out a general omniauth issue, probably

**Comment by awunder** [comment]
did some quick look and fired up the debugger.. it doesnt even break in the `setup_phase` method..(?)

![image](https://user-images.githubusercontent.com/13486613/126894791-01adbcc2-e73c-4462-adea-709127776897.png)

**Comment by frenesim** [comment]
I'm having the same problem here. Have you found what should be the endpoint?

**Comment by awunder** [comment]
nope, i put this on the stack hoping for the author to respond, eventually..

**Comment by frenesim** [comment]
Hey @awunder. I overcome this by setting the option name as per in the [omniauth strategy docs](https://github.com/omniauth/omniauth-oauth2#:~:text=Creating%20an%20OAuth2%20Strategy).
I endup to add this option while setting the provider, like this:
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :keycloak_openid, 'xxxCLIENTxxx', 'xxxKEYxxx',
           client_options: {site: 'https://auth.xxxDOMAINxxx.com', realm: 'xxxREALMxxx'},
           name: "what_ever"
end
```
Then I successfully request via POST
```erb
<%= button_to 'Sign In', '/auth/what_ever' %>
```
Hope it helps.

I think this info would be helpful in READMME

**Comment by awunder** [comment]
hey @frenesim thank you so much for this.. this indeed helped a lot!

**Comment by awunder** [comment]
i had to deal with some other stuff so i couldnt really test this out..

now i did, but the funny thing is, that now the auth callback url doesnt work..

i gave it a name via

![image](https://user-images.githubusercontent.com/13486613/128214849-001d2cb9-5357-42b0-a910-9fcfd4b7371d.png)

and now the redirect fails with a `No route matches [GET] "/auth/ofwd/callback"`

@frenesim did this work for you?

**Comment by awunder** [comment]
please disregard, i commented out  the callback route :facepalm:
