### ISSUE TITLE
Is the "/auth/" part mandatory in Keycloak's configuration URL?

### ISSUE THREAD

**Issue by fchampreux** [ccrockett/omniauth-keycloak#19]
To be integrated at corporate level, my RoR 5.2.4 application needs a new authentication provider: **Keycloak**.
Here, the Keycloak server URL to retrieve configuration information is: https://identity-a.bit.admin.ch/realms/bfs-sis-a

Which should correspond to the following configuration in config/inititalizers/devise.rb:
```
  config.omniauth :keycloak_openid,
    "BFS.SIS",
    client_options: { site: "https://identity-a.bit.admin.ch", realm: "bfs-sis-a" },
    strategy_class: OmniAuth::Strategies::KeycloakOpenId
```

Unfortunately, the configuration request issued by my application fails, as it is visible in this trace:
```
Started POST "/users/auth/keycloakopenid" for 127.0.0.1 at 2021-11-22 16:29:35 +0100
D, [2021-11-22T16:29:35.599250 #9892] DEBUG -- omniauth: (keycloakopenid) Going to get Keycloak configuration. URL: https://identity-a.bit.admin.ch/auth/realms/bfs-sis-a/.well-known/openid-configuration
E, [2021-11-22T16:29:35.667631 #9892] ERROR -- omniauth: (keycloakopenid) Keycloak configuration request failed with status: 404. URL: https://identity-a.bit.admin.ch/auth/realms/bfs-sis-a/.well-known/openid-configuration
D, [2021-11-22T16:29:35.667881 #9892] DEBUG -- omniauth: (keycloakopenid) Request phase initiated.
```

As you can see, the requested URL differs by the "**/auth/**" part, that seems to belong to the default URL of Keycloak. But our dedicated server's configuration appears to be different.
Reading the code of the gem, I see that this URL element cannot be changed.

Can you please let me know if my analysis is correct, and if we have a solution?
Thanks a lot!

**Comment by ccrockett** [comment]
I have implemented this feature in v1.4.0 of the gem based on your PR but without breaking existing implementations
