### ISSUE TITLE
Get Request is now Post Request

### ISSUE THREAD

**Issue by m-andreas** [ccrockett/omniauth-keycloak#23]
Why did the auth/keycloak route switch to post and whats the inteded functionality now? (I upgraded from 1.2 to 1.4)

Maybe I got the concept wrong, but I am using this route with redirect_to, which is not possible now anymore.

Could someone enlighten me? 
If there is any demand for that, and I am not the only only one with this issue, I could add it to the readme afterwards.

Thanks a lot for the great gem and the help!

**Comment by ccrockett** [comment]
This gem was updated to omniauth 2.0 between those versions, Omniauth 2.0 addresses some security issues see [omniauth wiki on upgrading to 2.0](https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0)
