### ISSUE TITLE
Expose id_token inside extra hash of auth hash

### ISSUE THREAD

**Issue by rah-wtag** [ccrockett/omniauth-keycloak#25]
In keycloak 17.0.0 and afterwards they have removed the support for `redirect_uri` on logout request. They suggest the usage of
`post_logout_redirect_uri` and `id_token_hint`. To use the RP initiated logout we therefore require the `id_token` . Unfortunately after digging around quite a bit, I found out that `id_token` is not exposed in the auth hash in omniauth-keycloak. the access_token.token is exposed , but the access_token['id_token'] is not exposed. By passing `scope: 'openid'` this id_token is available inside access_token['id_token']. Without this `id_token` it is not possible to use the RP initiated logout feature of keycloak. Do you think it is possible to expose this `id_token` inside the extra hash? 
Or maybe there is already a hidden configuration that I am missing?

**Comment by rah-wtag** [comment]
Hi I have created a PR that will expose the id_token here #26. 
Thank you!

**Comment by ccrockett** [comment]
Thanks for documenting this issue and PR to fix it. I've merged your PR and released a new version of the gem (1.4.1).

**Comment by rah-wtag** [comment]
Thank you so much for the new release 🎉
