### ISSUE TITLE
Adjust endpoints to updated Keycloak paths

### ISSUE THREAD

**Issue by kjoscha** [ccrockett/omniauth-keycloak#29]
With Keycloak 17 "/auth" was removed from all endpoints. Thus, endpoints as `http://localhost:8080/auth/realms/fdz/protocol/openid-connect/auth` have changed to `http://localhost:8080/realms/fdz/protocol/openid-connect/auth`.

See upgrading guide:
https://www.keycloak.org/docs/latest/upgrading/index.html

Workaround is to use the `--http-relative-path '/auth'` option with the keycloak start command

**Comment by ccrockett** [comment]
You should also be able to get this working by passing in the base_url client_option as an empty string (`client_options: {... base_url: '', ....}`), see [Configuration](https://github.com/ccrockett/omniauth-keycloak#configuration) section of the README.md

I will update the documentation more clear that this needs to be passed in when using Keycloak version >= 17 but I would prefer to not make it the default as I'm sure there are existing users that would prefer to not break their existing setup.

**Comment by epugh** [comment]
THanks for fixing this!   The updated burned me, and I was thinking "ugh, I am going to have to hack my app" so seeing this out was a nice surpirse!!!!!
