### ISSUE TITLE
Error: uninitialized constant OmniAuth::Strategies::KeycloakOpenId::MultiJson after gem update

### ISSUE THREAD

**Issue by fchampreux** [ccrockett/omniauth-keycloak#30]
My pplication is running on Ruby 2.7 / Rails 5.2.4 on Windows 10 and SUSE (SLES 15.SP3).
It uses Devise for authentication, with omniauth-keycloak, which worked fine for several months.

This morning I had tu run "bundle update" for an unrelated subject. After this update, invoking the link to Keycloak remote server for authentication issues the following error:
```
DEBUG -- omniauth: (keycloakopenid) Going to get Keycloak configuration. URL: https://identity-a.manage.ch/realms/bfs-sis-a/.well-known/openid-configuration
E, [2022-07-19T08:57:43.384693 #13364] ERROR -- omniauth: (keycloakopenid) Authentication failure! uninitialized constant OmniAuth::Strategies::KeycloakOpenId::MultiJson: NameError, uninitialized constant OmniAuth::Strategies::KeycloakOpenId::MultiJson
Processing by Users::OmniauthCallbacksController#failure as HTML
```
And redirects to the sign-in page.

The OmniAuth::Strategies::KeycloakOpenId::MultiJson constant does not exist in the project indeed. 
The closest constant OmniAuth::Strategies::KeycloakOpenId i used in the devise.rb initializer:
```
  config.omniauth :keycloak_openid,
    "BFS.SIS",
    client_options: { base_url: '', site: Rails.application.credentials.integration[:authentication_url], realm: "bfs-sis-a" },
    strategy_class: OmniAuth::Strategies::KeycloakOpenId
```

Installed gem versions are:

- devise (4.8.1)
- oauth2 (2.0.6)
- omniauth (2.1.0)
- omniauth-oauth2 (1.7.3)
- omniauth-keycloak (1.4.2)
- omniauth-rails_csrf_protection (1.0.1)

How could I solve this issue?

**Comment by ccrockett** [comment]
The quick fix is it looks like you need to include the [multi_json](https://rubygems.org/gems/multi_json) gem in your application.

The dirty details:
`omniauth-keycloak` (this project) depends on `omniauth-oauth2` which depends on `oauth2`. `oauth2` used to include `multi_json` as a dependency so we could just use the `multi_json` gem without worry. The `oauth2` gem has removed `multi_json` as a dependency in >=2.0.0, so if you are running `oauth2` >= 2.0.0 this error will occur.a

I should of made it an explicit dependency of this gem to begin with. Anyways, I will work on getting a new version of the gem out this week to fix this issue but in the meantime you should just be able to include the `multi_json` gem explicitly in your projects
