### ISSUE TITLE
When in test mode, setup phase tries to fetch Keycloak configuration

### ISSUE THREAD

**Issue by Kazhuu** [ccrockett/omniauth-keycloak#32]
I think the during the test mode setup phase should skip fetching the Keycloak configuration, so when testing you don't need to rely upon having a running Keycloak instance somewhere. This now makes it quite hard to test this omniauth strategy because of this requirement. 

I haven't looked at other omniauth strategies what they do but according to omniauth testing wiki [page](https://github.com/omniauth/omniauth/wiki/Integration-Testing). Omniauth is just supposed to redirect the user to the callback url with the mocked result. Now because of this external config fetch request, testing the callback behavior is harder than it needs to be I think.

I'm on the right track with this? I'd happy to make a PR about this.

EDIT:
I actually managed to test the login with the browser by mocking the keycloak configuration and certs api locally with WebMock. Either way I think code should not make external requests in test mode.

**Comment by ccrockett** [comment]
Thanks for the PR for this

**Comment by Kazhuu** [comment]
Would it possible to make a release with the fix? I could fix our test cases.

**Comment by ccrockett** [comment]
This fix has been released in version 1.5.0 or greater
