### ISSUE TITLE
Dependency update - json-jwt

### ISSUE THREAD

**Issue by a-gradina** [ccrockett/omniauth-keycloak#36]
Hi! Do you guys plan to update the dependencies so OpenSSL 3 can be used? From what I could make out, only `json-jwt` would need to be updated.

Cheers

**Comment by ccrockett** [comment]
Yeah, hopefully there aren't any breaking changes. I will try to get this resolved over the weekend.

**Comment by kjoscha** [comment]
any news here? :)

**Comment by kjoscha** [comment]
@a-gradina Have you found any workarounds to use the Gem in a ruby environment using OpenSSL 3?

**Comment by a-gradina** [comment]
> @a-gradina Have you found any workarounds to use the Gem in a ruby environment using OpenSSL 3?

No. To be honest I haven't looked much into it, as it's not on our priority list. If time allows, I'll take a closer look.

**Comment by ccrockett** [comment]
This should be fixed in release version 1.5.0 or greater
